language: node_js

node_js:
  - "0.10"

rvm:
  - "2.0.0"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli@0.1.x karma@0.8.x mocha@1.17.x
  - cd server
  - npm install --quiet
  - grunt
  - sleep 3 # give server some time to start
  - cd ../client
  - gem install sass # necessary for grunt-contrib-sass
  - npm install --quiet
  - cd ..


script:
  - cd client
  - grunt
  - cd ../server
  - grunt
