language: node_js

node_js:
  - "0.10"

rvm:
  - "2.0.0"

before_script:
  - ./.travis/scripts/install_chrome.sh
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli@0.1.x karma@0.8.x
  - cd client
  - gem install sass # necessary for grunt-contrib-sass
  - npm install --quiet
  # - cd server
  # - npm install --quiet
  # - node server.js &
  # - sleep 3 # give server some time to start

script: grunt
